ask/ask/urls.py
from django.conf.urls import url, include

from django.contrib import admin

admin.autodiscover()

import qa.urls

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'ask.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(qa.urls, namespace='qa'))
]

ask/qa/urls.py
from django.conf.urls import url, include

import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'ask.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.new, name='main'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^question/(?P<q_id>\d+)/$', views.view_question, name='question'),
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^popular/$', views.popular, name='popular'),
    url(r'^new/$', views.new, name='new'),
]

ask/qa/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from .local_settings import *


class QuestionManager(models.Manager):
    def __get_by(self, param, reverse=False, only_active=True):
        if reverse:
            param = '-' + param
        result = Question.objects.all()
        if only_active:
            result = result.filter(active=True)
        return result.order_by(param)

    def new(self):
        return self.__get_by('pk', reverse=True)

    def popular(self):
        return self.__get_by('rating', reverse=True)


class Entry(models.Model):
    text = models.TextField()
    #TODO: change to DateTime
    added_at = models.DateField(default=datetime.now)
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Question(Entry):
    objects = QuestionManager()

    author = models.ForeignKey(User, blank=True, null=True)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    rating = models.IntegerField(default=0)
    likes = models.ManyToManyField(User, blank=True, null=True, related_name='likes_user')

    def __str__(self):
        return "Question #%d" % self.id

    def get_url(self):
        return reverse('qa:question', kwargs={'q_id': self.pk})


class Answer(Entry):
    author = models.ForeignKey(User, blank=True, null=True)
    question = models.ForeignKey(Question)

    def __str__(self):
        return "Answer #%d" % self.id

ask/qa/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Question, Answer

from .local_settings import *


class GenericForm(forms.Form):
    # def __init__(self, model, user, *args, **kwargs):
    def __init__(self, model, *args, **kwargs):
        self.model = model
        # self.user = user
        super(forms.Form, self).__init__(*args, **kwargs)

    def clean(self):
        # no checks for now
        if False:
            raise forms.ValidationError()
        return self.cleaned_data

    def save(self):
        # self.cleaned_data['author'] = self.user
        obj = self.model(**self.cleaned_data)
        obj.save()
        return obj


class AskForm(GenericForm):
    title = forms.CharField(max_length=TITLE_MAX_LENGTH)
    text = forms.CharField(widget=forms.Textarea)

    # def __init__(self, user, *args, **kwargs):
    #     super(self.__class__, self).__init__(Question, user, *args, **kwargs)
    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(Question, *args, **kwargs)


class AnswerForm(GenericForm):
    text = forms.CharField(widget=forms.Textarea)

    # def __init__(self, question_id, user, *args, **kwargs):
    def __init__(self, question_id, *args, **kwargs):
        self.question_id = question_id
        # super(self.__class__, self).__init__(Answer, user, *args, **kwargs)
        super(self.__class__, self).__init__(Answer, *args, **kwargs)

    def save(self):
        self.cleaned_data['question_id'] = self.question_id
        return super(self.__class__, self).save()


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput, max_length=255)


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput, max_length=255)

    def save(self):
        obj = User.objects.create_user(**self.cleaned_data)
        obj.save()
        return obj

    def clean_username(self):
        data = self.cleaned_data['username']
        if len(data) < MIN_USERNAME_LENGTH:
            raise forms.ValidationError(
                'Minimum length of Username is %(num)s symbols',
                params={'num': MIN_USERNAME_LENGTH}
            )
        try:
            User.objects.get(username=data)
        except User.DoesNotExist:
            return data
        else:
            raise forms.ValidationError(
                'User already exists'
            )

    def clean_password(self):
        data = self.cleaned_data['password']
        if len(data) < MIN_PASSWORD_LENGTH:
            raise forms.ValidationError(
                'Minimum length of Password is %(num)s symbols',
                params={'num': MIN_PASSWORD_LENGTH}
            )
        return data

ask/qa/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.decorators.http import require_GET
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user, logout as logout_user

from .forms import AskForm, AnswerForm, LoginForm, SignUpForm
from models import Question, Answer

DEFAULT_PAGE_VALUE = 1
DEFAULT_LIMIT_VALUE = 10
INVALID_AUTH_MESSAGE = 'Invalid login or password'


@require_GET
def base(request, view):
    try:
        page = int(request.GET.get('page', DEFAULT_PAGE_VALUE))
        assert 0 < page
    except:
        page = DEFAULT_PAGE_VALUE
    try:
        limit = int(request.GET.get('limit', DEFAULT_LIMIT_VALUE))
        assert 0 < limit <= DEFAULT_LIMIT_VALUE
    except:
        limit = DEFAULT_LIMIT_VALUE
    paginator = Paginator(getattr(Question.objects, view)(), limit)
    paginator.baseurl = '%s?limit=%d&page=' % (reverse('qa:%s' % view), limit)
    page = paginator.page(min(page, paginator.num_pages))
    context = {
        'page': page,
        'questions': page.object_list,
        'paginator': paginator
    }
    return render(request, 'qa/%s.html' % view, context)


@require_GET
def new(request):
    return base(request, 'new')


@require_GET
def popular(request):
    return base(request, 'popular')


# @login_required
def view_question(request, q_id):
    question = get_object_or_404(Question, id=q_id)
    if not question.active:
        raise Http404()
    if request.method == 'POST':
        # form = AnswerForm(q_id, request.user, request.POST)
        form = AnswerForm(q_id, request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(question.get_url())
    else:
        # form = AnswerForm(q_id, request.user)
        form = AnswerForm(q_id)
    answers = Answer.objects.filter(question=question)
    context = {
        'question': question,
        'answers': answers,
        'form': form
    }
    return render(request, 'qa/question.html', context)


# @login_required
def ask(request):
    if request.method == 'POST':
        # form = AskForm(request.user, request.POST)
        form = AskForm(request.POST)
        if form.is_valid():
            question = form.save()
            return HttpResponseRedirect(question.get_url())
    else:
        # form = AskForm(request.user)
        form = AskForm()
    return render(request, 'qa/ask.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=request.POST.get('username', None),
                password=request.POST.get('password', None),
            )
            if user is not None:
                login_user(request, user)
                next_page = request.GET.get('next', '/')
                return HttpResponseRedirect(next_page)
        form.add_error(None, INVALID_AUTH_MESSAGE)
    else:
        form = LoginForm()
    return render(request, 'qa/login.html', {'form': form})


@login_required
def logout(request):
    logout_user(request)
    next_page = request.GET.get('next', '/')
    return HttpResponseRedirect(next_page)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login_user(request, user)
            next_page = request.GET.get('next', '/')
            return HttpResponseRedirect(next_page)
    else:
        form = SignUpForm()
    return render(request, 'qa/login.html', {'form': form})


def test(request, *args, **kwargs):
    return HttpResponse('OK')

ask/templates/qa/ask.html
{% extends 'qa/base.html' %}
{% block title %}
    Ask a question
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form.as_p }}
        </fieldset>
        <button type="submit">Send</button>
    </form>

{% endblock %}

ask/templates/qa/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Generic Title{% endblock %}</title>
</head>
<body>
<div>
    {% if request.user.is_authenticated %}
        You are logged as {{ request.user.username }} (<a href="{% url 'qa:logout' %}?next={{ request.path }}">logout</a>)
    {% else %}
        Please, <a href="{% url 'qa:login' %}">login</a> or <a href="{% url 'qa:signup' %}">sign up</a>
    {% endif %}
</div>
<div>
    {% block header %}
        <ul class="navigation">
            <li><a href="{% url 'qa:main' %}">Return to main</a></li>
            <li><a href="{% url 'qa:ask' %}">Ask a new question</a></li>
        </ul>
    {% endblock %}
</div>
<div>{% block content %}Generic Content{% endblock %}</div>
<div>{% block footer %}Generic Footer{% endblock %}</div>
</body>
</html>

ask/templates/qa/login.html
{% extends 'qa/base.html' %}
{% block title %}
    Login
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form.as_p }}
        </fieldset>
        <button type="submit">Send</button>
    </form>
{% endblock %}

ask/templates/qa/new.html
{% extends 'qa/base.html' %}
{% block title %}
    Recent questions
{% endblock %}
{% block content %}
    {% if questions %}
        New questions:
        <ul>
            {% for question in questions %}
                <li><a href="{{ question.get_url }}">{{ question.title }}</a></li>
            {% endfor %}
        </ul>
        <div>
        {% for pagination_page in paginator.page_range %}
            <a href="{{ paginator.baseurl }}{{ pagination_page }}">{{ pagination_page }}</a>
        {% endfor %}
        </div>
    {% else %}
        Sorry, no questions available!
    {% endif %}
{% endblock %}

ask/templates/qa/popular.html
{% extends 'qa/base.html' %}
{% block title %}
    The most popular questions
{% endblock %}
{% block content %}
    {% if questions %}
        Popular questions:
        <ul>
            {% for question in questions %}
                <li><a href="{{ question.get_url }}">{{ question.title }}</a></li>
            {% endfor %}
        </ul>
        <div>
        {% for pagination_page in paginator.page_range %}
            <a href="{{ paginator.baseurl }}{{ pagination_page }}">{{ pagination_page }}</a>
        {% endfor %}
        </div>
    {% else %}
        Sorry, no questions available!
    {% endif %}
{% endblock %}

ask/templates/qa/question.html
{% extends 'qa/base.html' %}
{% block title %}
    {{ question.title }}
{% endblock %}
{% block content %}
    <div>{{ question.text }}</div>
    {% if answers %}
            {% for answer in answers %}
                <div>{{ answer.text }}</div>
            {% endfor %}
    {% else %}
        No answers available.
    {% endif %}
{% endblock %}

ask/templates/qa/signup.html
{% extends 'qa/base.html' %}
{% block title %}
    Sign Up
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form.as_p }}
        </fieldset>
        <button type="submit">Send</button>
    </form>
{% endblock %}